image: alpine:latest

pages:
  stage: deploy
  script:
  - cd public/programs
  - echo "<!DOCTYPE html><head><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.3/css/bootstrap.min.css" integrity="sha512-oc9+XSs1H243/FRN9Rw62Fn8EtxjEYWHXRvjS43YtueEewbS6ObfXcJNyohjHqVKFPoXXUxwc+q1K7Dee6vv9g==" crossorigin="anonymous" /></head><body><div class='container lead'><h1 class='mt-2'>Programs</h1><hr />" > ./index.html
  - find . -type f -iname '*.pdf' | sort -r | xargs -I '{}' echo "<a href='{}'>{}</a><br/><hr/>" >> ./index.html
  - echo "</div></body></html>" >> ./index.html
  artifacts:
    paths:
    - public
  only:
  - master
